const questions = [
  {
    id: 1,
    question: "Nigeria is located on which continent?",
    options: {
      A: "Asia",
      B: "Africa",
      C: "Europe",
      D: "South America",
    },
    answer: "B",
    category: "Geography",
  },
  {
    id: 2,
    question: "What is the capital city of Nigeria?",
    options: {
      A: "Lagos",
      B: "Ibadan",
      C: "Abuja",
      D: "Benin",
    },
    answer: "C",
    category: "Nigeria",
  },
  {
    id: 3,
    question: "Which ocean is the largest in the world?",
    options: {
      A: "Atlantic Ocean",
      B: "Indian Ocean",
      C: "Arctic Ocean",
      D: "Pacific Ocean",
    },
    answer: "D",
    category: "Geography",
  },
  {
    id: 4,
    question: "How many days are there in a leap year?",
    options: {
      A: "365",
      B: "364",
      C: "366",
      D: "367",
    },
    answer: "C",
    category: "General",
  },
  {
    id: 5,
    question: "Which of these is NOT a Nigerian state?",
    options: {
      A: "Oyo",
      B: "Kwara",
      C: "Kano",
      D: "Accra",
    },
    answer: "D",
    category: "Nigeria",
  },
  {
    id: 6,
    question: "The sun rises from the:",
    options: {
      A: "North",
      B: "South",
      C: "East",
      D: "West",
    },
    answer: "C",
    category: "General",
  },
  {
    id: 7,
    question: "What gas do humans need for breathing?",
    options: {
      A: "Carbon dioxide",
      B: "Oxygen",
      C: "Nitrogen",
      D: "Hydrogen",
    },
    answer: "B",
    category: "Science",
  },
  {
    id: 8,
    question: "Which planet is known as the Red Planet?",
    options: {
      A: "Venus",
      B: "Jupiter",
      C: "Mars",
      D: "Saturn",
    },
    answer: "C",
    category: "Science",
  },
  {
    id: 9,
    question: "How many continents are there in the world?",
    options: {
      A: "5",
      B: "6",
      C: "7",
      D: "8",
    },
    answer: "C",
    category: "Geography",
  },
  {
    id: 10,
    question: "Which of these is a renewable source of energy?",
    options: {
      A: "Coal",
      B: "Petrol",
      C: "Solar",
      D: "Diesel",
    },
    answer: "C",
    category: "Science",
  },
  {
    id: 11,
    question: "Nigeria gained independence in which year?",
    options: {
      A: "1957",
      B: "1960",
      C: "1963",
      D: "1970",
    },
    answer: "B",
    category: "Nigeria",
  },
  {
    id: 12,
    question: "Which organ pumps blood in the human body?",
    options: {
      A: "Lungs",
      B: "Brain",
      C: "Heart",
      D: "Kidney",
    },
    answer: "C",
    category: "Science",
  },
  {
    id: 13,
    question: "What is the official language of Nigeria?",
    options: {
      A: "Yoruba",
      B: "Hausa",
      C: "Igbo",
      D: "English",
    },
    answer: "D",
    category: "Nigeria",
  },
  {
    id: 14,
    question: "Which number comes next: 2, 4, 6, 8, ?",
    options: {
      A: "9",
      B: "10",
      C: "11",
      D: "12",
    },
    answer: "B",
    category: "Logic",
  },
  {
    id: 15,
    question: "Which of these animals is a mammal?",
    options: {
      A: "Snake",
      B: "Lizard",
      C: "Whale",
      D: "Frog",
    },
    answer: "C",
    category: "Science",
  },
  {
    id: 16,
    question: "Which direction is opposite to North?",
    options: {
      A: "East",
      B: "West",
      C: "South",
      D: "Up",
    },
    answer: "C",
    category: "General",
  },
  {
    id: 17,
    question: "Which of these is used to measure temperature?",
    options: {
      A: "Barometer",
      B: "Thermometer",
      C: "Speedometer",
      D: "Ammeter",
    },
    answer: "B",
    category: "Science",
  },
  {
    id: 18,
    question: "How many hours are there in a day?",
    options: {
      A: "12",
      B: "18",
      C: "24",
      D: "36",
    },
    answer: "C",
    category: "General",
  },
  {
    id: 19,
    question: "Which of these is a Nigerian currency unit?",
    options: {
      A: "Dollar",
      B: "Pound",
      C: "Euro",
      D: "Naira",
    },
    answer: "D",
    category: "Nigeria",
  },
  {
    id: 20,
    question: "What force pulls objects toward the Earth?",
    options: {
      A: "Magnetism",
      B: "Friction",
      C: "Gravity",
      D: "Electric force",
    },
    answer: "C",
    category: "Physics",
  },
  {
    id: 21,
    question: "Which of these is a primary color?",
    options: {
      A: "Green",
      B: "Purple",
      C: "Red",
      D: "Pink",
    },
    answer: "C",
    category: "General",
  },
  {
    id: 22,
    question: "Which device is used to make phone calls?",
    options: {
      A: "Television",
      B: "Radio",
      C: "Telephone",
      D: "Calculator",
    },
    answer: "C",
    category: "Technology",
  },
  {
    id: 23,
    question: "Which of these is a body of water?",
    options: {
      A: "Desert",
      B: "Mountain",
      C: "River",
      D: "Forest",
    },
    answer: "C",
    category: "Geography",
  },
  {
    id: 24,
    question: "How many letters are there in the English alphabet?",
    options: {
      A: "24",
      B: "25",
      C: "26",
      D: "27",
    },
    answer: "C",
    category: "General",
  },
  {
    id: 25,
    question: "Which part of a computer shows output?",
    options: {
      A: "Keyboard",
      B: "Mouse",
      C: "Monitor",
      D: "CPU",
    },
    answer: "C",
    category: "Technology",
  },
  {
    id: 26,
    question: "Which season comes after the rainy season in Nigeria?",
    options: {
      A: "Winter",
      B: "Dry season",
      C: "Spring",
      D: "Autumn",
    },
    answer: "B",
    category: "Nigeria",
  },
  {
    id: 27,
    question: "What shape has three sides?",
    options: {
      A: "Square",
      B: "Rectangle",
      C: "Triangle",
      D: "Circle",
    },
    answer: "C",
    category: "Math",
  },
  {
    id: 28,
    question: "Which of these is used to write?",
    options: {
      A: "Spoon",
      B: "Pen",
      C: "Plate",
      D: "Cup",
    },
    answer: "B",
    category: "General",
  },
  {
    id: 29,
    question: "Which planet is closest to the Sun?",
    options: {
      A: "Earth",
      B: "Venus",
      C: "Mercury",
      D: "Mars",
    },
    answer: "C",
    category: "Science",
  },
  {
    id: 30,
    question: "Which of these is a means of transportation?",
    options: {
      A: "Chair",
      B: "Table",
      C: "Car",
      D: "Bed",
    },
    answer: "C",
    category: "General",
  },
];
export default questions;
